import type { Business, Category } from "@/src/types";

/**
 * Artwork lives under /public/images in a self-contained,
 * documented structure (see IMAGE_GUIDE.md at the project
 * root). Everything is generated by scripts/generate-images.mjs.
 */

/** Vendor imagery — six deterministic variants per category. */
export const artPath = (slug: string, variant: number): string =>
  `/images/vendors/${slug}-${variant % 6}.svg`;

export const categoryArt = (category: Category, variant = 0): string =>
  artPath(category.artSlug, variant);

export const businessCoverArt = (business: Business): string => {
  const [primaryCategoryId] = business.categoryIds;
  const slug = primaryCategoryId?.replace("cat-", "") ?? "technology";
  return artPath(slug, business.artVariant);
};

export const businessGalleryArt = (business: Business): string[] => {
  const [primaryCategoryId] = business.categoryIds;
  const slug = primaryCategoryId?.replace("cat-", "") ?? "technology";
  return [1, 2, 3].map((offset) =>
    artPath(slug, business.artVariant + offset)
  );
};

export const productArt = (business: Business, productIndex: number): string => {
  const [primaryCategoryId] = business.categoryIds;
  const slug = primaryCategoryId?.replace("cat-", "") ?? "technology";
  return artPath(slug, business.artVariant + productIndex + 1);
};

/** Category tiles — the canonical composition per category. */
export const categoryTileArt = (category: Category): string =>
  `/images/categories/${category.artSlug}.svg`;

/** Homepage hero backdrop (1600×1000, 16:10). */
export const heroArt = (): string => "/images/hero/hero-open-bazaar.svg";

/** Upcoming Open Bazaar event band (1600×900, 16:9). */
export const eventArt = (): string => "/images/events/open-bazaar-5.svg";

/** Campus stalls scene (1200×900, 4:3). */
export const campusArt = (): string => "/images/campus/campus-stalls.svg";
